NamingConventionTool/src/main/java/org/openepics/names/model/AppInfo.java
/*
* Copyright (c) 2014 European Spallation Source
* Copyright (c) 2014 Cosylab d.d.
*
* This file is part of Naming Service.
* Naming Service is free software: you can redistribute it and/or modify it under
* the terms of the GNU General Public License as published by the Free
* Software Foundation, either version 2 of the License, or any newer version.
*
* This program is distributed in the hope that it will be useful, but WITHOUT
* ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
* FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
* more details.
*
* You should have received a copy of the GNU General Public License along with
* this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
*/

package org.openepics.names.model;

import javax.persistence.Entity;

/**
 * A singleton entity representing the installed Naming Tool application. At the moment the presence of this entity is
 * only used to indicate that the database has been initialized. Later it could carry things like schema version and
 * application configuration.
 *
 * @author Marko Kolar
 */
@Entity
public class AppInfo extends Persistable {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 8040585866896629942L;
	private int schemaVersion;
  
    public int getSchemaVersion() { return schemaVersion; }
    
    public void incrementSchemaVersion() { schemaVersion++; }
}

NamingConventionTool/src/main/java/org/openepics/names/business/UserAction.java
package org.openepics.names.business;

import java.util.Date;

import org.openepics.names.model.UserAccount;

public class UserAction {

    private final Date date;
    private final String message;
    private final UserAccount user;

    /**
     * Constructor
     *
     * @param date the date
     * @param message the user message
     * @param user the user
     */
    public UserAction(Date date, String message, UserAccount user) {
        this.date = date;
        this.message = message;
        this.user = user;
    }

    /**
     * @return the date
     */
    public Date getDate() {
        return date;
    }

    /**
     * @return the message
     */
    public String getMessage() {
        return message;
    }

    /**
     * @return the user
     */
    public UserAccount getUser() {
        return user;
    }

}

NamingConventionTool/src/main/java/org/openepics/names/ui/common/LoginController.java
package org.openepics.names.ui.common;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import org.openepics.names.business.NameType;
import org.openepics.names.services.SessionService;
import org.openepics.names.ui.parts.NamePartsController;
import se.esss.ics.rbac.loginmodules.service.Message;

/**
 * A UI controller bean for the login / logout button and form.
 *
 * @author Vasu V
 * @author K. Rathsman
 */
@ManagedBean
@ViewScoped
public class LoginController implements Serializable {

    private static final long serialVersionUID = 7124872676453151325L;
    private static final Logger LOGGER = Logger.getLogger(LoginController.class.getName());
    @Inject
    private SessionService sessionService;
    private String inputUsername;
    private String inputPassword;

    @PostConstruct
    public synchronized void init() {

    }

    public String getActiveIndex() {
        String viewId = FacesContext.getCurrentInstance().getViewRoot().getViewId();
        switch (viewId) {
            case "/index.xhtml":
                return "0";
            case "/about.xhtml":
                return "1";
            case "/devices.xhtml":
                return "2";
            case "/parts.xhtml":
                String type = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("type");
                if (type == null) {
                    FacesContext facesContext = FacesContext.getCurrentInstance();
                    NamePartsController namePartsController = (NamePartsController) facesContext.getApplication().getExpressionFactory().createValueExpression(facesContext.getELContext(), "#{namePartsController}", Object.class).getValue(facesContext.getELContext());
                    type = namePartsController.getType();
                }
                if (type != null && type.equals(NameType.AREA_STRUCTURE.toString())) {
                    return "3";
                } else if (type != null && type.equals(NameType.DEVICE_STRUCTURE.toString())) {
                    return "4";
                } else {
                    return "0";
                }
            case "/help.xhtml":
                return "5";
            default:
                return "0";
        }
    }

    public void prepareLoginPopup() {
        inputUsername = null;
        clearPassword();
    }

    public void clearPassword() {
        inputPassword = null;
    }

    public synchronized void signIn() throws IOException {
        try {
            Message m = sessionService.login(inputUsername, inputPassword);
            if (m.isSuccessful()) {
                LOGGER.log(Level.INFO, "Login successful for " + getUsername());
            } else {
                showMessage(new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed to sign in", m.getMessage()));
                LOGGER.log(Level.INFO, "Login failed for " + inputUsername);
            }
        } catch (Exception e) {
            showMessage(new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed to sign in", e.getMessage()));
            LOGGER.log(Level.SEVERE, "Cannot sign in", e.getMessage());

        } finally {
            clearPassword();
            sessionService.update();
        }
    }

    public boolean isLoggedIn() {
        return sessionService.isLoggedIn();
    }

    public String getUsername() {
        return sessionService.getUsername();
    }

    public synchronized String signOut() {
        try {
            Message m = sessionService.logout();
            if (m.isSuccessful()) {
                LOGGER.log(Level.INFO, "Logout successful");

            } else {
                showMessage(new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed to sign out", m.getMessage()));
                LOGGER.log(Level.SEVERE, "Failed to sign out", m.getMessage());
            }
        } catch (Exception e) {
            showMessage(new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed to sign out", e.getMessage()));
            LOGGER.log(Level.SEVERE, "Failed to sign out ", e.getMessage());

        } finally {
            prepareLoginPopup();
            sessionService.update();
        }
        return FacesContext.getCurrentInstance().getViewRoot().getViewId();

    }

    public String getInputUsername() {
        return inputUsername;
    }

    public void setInputUsername(String inputUsername) {
        this.inputUsername = inputUsername;
    }

    public String getInputPassword() {
        return inputPassword;
    }

    public void setInputPassword(String inputPassword) {
        this.inputPassword = inputPassword;
    }

    /**
     * shows the faces message
     *
     * @param message the faces message
     */
    public void showMessage(FacesMessage message) {
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
}

NamingConventionTool/src/main/java/org/openepics/names/ui/parts/NamePartsController.java
/*
 * This software is Copyright by the Board of Trustees of Michigan
 * State University (c) Copyright 2012.
 *
 * You may use this software under the terms of the GNU public license
 *  (GPL). The terms of this license are described at:
 *       http://www.gnu.org/licenses/gpl.txt
 *
 * Contact Information:
 *   Facility for Rare Isotope Beam
 *   Michigan State University
 *   East Lansing, MI 48824-1321
 *   http://frib.msu.edu
 *
 *
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 */
package org.openepics.names.ui.parts;

import com.google.common.base.Preconditions;
import com.google.common.collect.Lists;
import com.google.common.collect.Sets;

import org.openepics.names.business.NameElement;
import org.openepics.names.business.NameFilter;
import org.openepics.names.business.NameType;
import org.openepics.names.business.RowData;
import org.openepics.names.nameViews.NameView;
import org.openepics.names.nameViews.NameViewProvider;
import org.openepics.names.operation.Add;
import org.openepics.names.operation.Approve;
import org.openepics.names.operation.Cancel;
import org.openepics.names.operation.Delete;
import org.openepics.names.operation.Modify;
import org.openepics.names.operation.NameOperation;
import org.openepics.names.operation.Reject;
import org.openepics.names.operation.SingleNameOperation;
import org.openepics.names.ui.common.TreeNodeManager;
import org.openepics.names.util.As;
import org.primefaces.event.FlowEvent;
import org.primefaces.event.NodeSelectEvent;
import org.primefaces.event.NodeUnselectEvent;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;
import javax.annotation.Nullable;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import java.io.Serializable;
import java.util.List;
import java.util.Set;
import org.openepics.names.nameViews.TransactionBean;
import org.openepics.names.operation.CheckDevices;
import org.openepics.names.services.SessionService;
import org.openepics.names.ui.common.LoginController;
import org.openepics.names.util.ValidationException;

/**
 * A UI controller bean for the Logical Area Structure and Device Category Structure screens.
 *
 * @author Vasu V
 * @author Karin Rathsman
 */
@ManagedBean
@ViewScoped
public class NamePartsController implements Serializable {

    private static final long serialVersionUID = 3723235418421156956L;
    @Inject
    private TreeNodeManager treeNodeManager;
    @Inject
    private NameViewProvider nameViewProvider;
    @Inject
    private TransactionBean transactionBean;
    @Inject
    private LoginController loginController;
    @Inject 
    private SessionService sessionService;

    private List<RowData> historyRevisionsAsRowData;
    private TreeNode viewRoot;
    private TreeNode[] selectedNodes;
    private NameType nameType;
    private Wizard wizard;
    private NameOperation nameOperation;

    /**
     * @return the type
     */
    public String getType() {
        return nameType != null ? nameType.toString() : NameType.AREA_STRUCTURE.toString();
    }

    /**
     * initializes the bean.
     */
    @PostConstruct
    public void init() {
        String structure = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("type");
        nameType = NameType.get(structure);
        update();
    }

    /**
     * updates all relevant data after changes.
     */
    public synchronized void update() {
        viewRoot = As.notNull(treeNodeManager.getStructureTree(null, nameType));
        setSelectedNodes(null);
        nameOperation = null;
        wizard = null;
    }

    /**
     * expands all nodes in the tree.
     */
    public synchronized void onExpandAll() {
        treeNodeManager.expandAll(viewRoot);
    }

    /**
     * collapses all nodes in the tree
     */
    public synchronized void onCollapseAll() {
        treeNodeManager.collapseAll(viewRoot);
    }

    /**
     * @return the view filter used in tables and trees.
     */
    public NameFilter getViewFilter() {
        return treeNodeManager.getNameFilter();
    }

    /**
     * @return the nameOperation
     */
    public NameOperation getNameOperation() {
        return nameOperation;
    }

    /**
     *
     * @return tru if the history can be shown for selected name
     */
    public boolean canShowHistory() {
        return selectedNodes != null && selectedNodes.length == 1;
    }

    /**
     * prepare for the history popup
     */
    public void prepareHistoryPopup() {
        NameView selectedNameView = canShowHistory() ? TreeNodeManager.nameView(selectedNodes[0]) : null;
        historyRevisionsAsRowData = nameViewProvider.getHistoryRevisionsAsRowData(selectedNameView);
        if(selectedNameView ==null || historyRevisionsAsRowData==null || historyRevisionsAsRowData.isEmpty()){
            throw new IllegalStateException("History empty");
        }
    }

    /**
     * @return the list of all revisionsPair as row Data of the selected node.
     */
    public List<RowData> getHistoryRevisionsAsRowData() {
        return historyRevisionsAsRowData;
    }

    /**
     *
     * @return the root of the name View tree.
     */
    public TreeNode getViewRoot() {
        return viewRoot != null ? viewRoot : new DefaultTreeNode(null, null);
    }

    /**
     * @return the selected tree nodes
     */
    public TreeNode[] getSelectedNodes() {
        return selectedNodes;
    }

    /**
     * sets the selected Nodes
     *
     * @param selectedNodes array containing the selected nodes
     */
    public void setSelectedNodes(TreeNode[] selectedNodes) {
        this.selectedNodes = selectedNodes != null ? selectedNodes : new TreeNode[0];
    }

    /**
     * @param actionString indicating the required operation
     * @return true if the selected names can be operated on
     */
    public boolean can(String actionString) {
        try {
            nameOperation(actionString).validateOnSelect();
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * @param actionString indicating the required operation
     * @return true if the selected names can be operated on
     */
    public boolean rendered(String actionString) {
        try {
            nameOperation(actionString).validateUser(sessionService.isEditor(), sessionService.isSuperUser());
            return true;
        } catch (Exception e) {
            return false;
        }
    }


    /**
     *
     * @param actionString
     * @return new name operation of instance specified by the actionString
     */
    private NameOperation nameOperation(String actionString) {
        Set<NameView> selectedNameViews = Sets.newHashSet();
        for (TreeNode treeNode : selectedNodes) {
            selectedNameViews.add(TreeNodeManager.nameView(treeNode));
        }
        NameView rootView = TreeNodeManager.nameView(viewRoot);
        switch (actionString) {
            case "add":
                return new Add(selectedNameViews, rootView);
            case "approve":
                return new Approve(selectedNameViews, rootView);
            case "cancel":
                return new Cancel(selectedNameViews, rootView);
            case "delete":
                return new Delete(selectedNameViews, rootView);
            case "modify":
                return new Modify(selectedNameViews, rootView);
            case "reject":
                return new Reject(selectedNameViews, rootView);
            case "checkDevices":
                return new CheckDevices(selectedNameViews, rootView);
            default:
                 throw new UnsupportedOperationException();
        }
    }

    /**
     * Submits the nameOperation.
     *
     */
    public synchronized void onSubmit() {
        FacesMessage message;
        message = transactionBean.submit(nameOperation);
        if(nameOperation instanceof Add){
            TreeNode parentNode = treeNodeManager.nodeOf(viewRoot, ((Add) nameOperation).getParentView());
            if(parentNode!=null){
                treeNodeManager.setExpanded(parentNode,true);
                treeNodeManager.expandParents(parentNode);
            }
        }
        update();
        loginController.showMessage(message);
    }

    /**
     *
     * @return true if the name operation can be submitted.
     */
    public boolean canSubmit() {
        if (nameOperation == null || nameOperation.isMessageRequired() && nameOperation.getMessage() == null) {
            //			showMessage(null, FacesMessage.SEVERITY_ERROR, "Validation Error", "Please enter a message");
            return false;
        } else {
            return true;
        }
    }

    /**
     * @return the wizard
     */
    public Wizard getWizard() {
        return wizard;
    }

    /**
     * prepare the operation dialog
     *
     * @param actionString string specifying the operation to be performed.
     */
    public void prepareOperationDialog(String actionString) {
        this.nameOperation = nameOperation(actionString);
        if (nameOperation instanceof SingleNameOperation) {
            this.wizard = new Wizard((SingleNameOperation) nameOperation);
        }
    }

    /**
     * Subclass to control the wizard for single name operation
     *
     * @author karinrathsman
     *
     */
    public class Wizard {

        private SiteForSuperSection siteForSuperSection;
        private TreeNode rootTree;
        private @Nullable
        TreeNode nameViewNode;
        private @Nullable
        TreeNode parentViewNode;
        private SingleNameOperation singleNameOperation;
        private final List<String> tabs = Lists.newArrayList("namePartTab", "parentTab", "descriptionTab", "finishTab");

        /**

NamingConventionTool/src/main/webapp/api-manual.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
	template="/WEB-INF/namesTemplate.xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:fc="http://java.sun.com/jsf/composite/comps">

	<ui:define name="content">
	<ui:fragment rendered="#{loginController.loggedIn}">
	

		<div class="ui-treetable-scrollable-body" id="apiManualDiv">

			<ui:param name="restRoot"
				value="#{request.scheme}://#{request.serverName}:#{request.serverPort}#{request.contextPath}/rest" />


			<div style="text-align: left">

				<h2>#{msgs.title} API Manual</h2>
				<p>
					Data in the Naming Service can be accessed programmatically through
					a <a
						href="http://en.wikipedia.org/wiki/Representational_state_transfer"
						target="_blank">RESTful</a> Application Programming Interface
					(API). The Naming System API follows <a href="http://semver.org/"
						target="_blank">Semantic Versioning</a> for its version numbers.
					The current API version number is #{msgs.apiversion}.
				</p>

				<h3>Representations</h3>

				The representations of the resources must be specified through HTTP
				ACCEPT header. This API supports JSON and XML representations.
				Examples:
				<ul>
					<li>Accept: application/json</li>
					<li>Accept: application/xml</li>
				</ul>
				<h3>Base URL</h3>
				The base URL for Resource Identifiers is #{restRoot}.
				<h3>Resources</h3>
				<p:panelGrid style="text-align: left">
					<f:facet name="header">
						<p:row>
							<p:column>Name</p:column>
							<p:column>Method</p:column>
							<p:column>Resource ID</p:column>
							<p:column>Description</p:column>
							<p:column>Example</p:column>
						</p:row>
					</f:facet>
					<p:row>
						<p:column>All Device Names</p:column>
						<p:column>GET</p:column>
						<p:column>/deviceNames</p:column>
						<p:column>List of all device names</p:column>
						<p:column>#{restRoot}/deviceNames</p:column>
					</p:row>
					<p:row>
						<p:column>Device Name With UUID</p:column>
						<p:column>GET</p:column>
						<p:column>/deviceNames/{uuid}</p:column>
						<p:column>Information of device name for given UUID. </p:column>
						<p:column>#{restRoot}/deviceNames/354fc899-add8-494c-a62e-1250837e1135</p:column>
					</p:row>
				</p:panelGrid>
			</div>
		</div>
		</ui:fragment>
	</ui:define>

</ui:composition>

NamingConventionTool/src/main/webapp/expired.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/namesTemplate.xhtml"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:fc="http://java.sun.com/jsf/composite/comps">

    <ui:define name="content">
        Your session has expired.
        <p><a href="#{requestScope['javax.servlet.error.request_uri']}">Return to the application.</a></p>
    </ui:define>

</ui:composition>

NamingConventionTool/src/main/webapp/parts.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>

<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                template="/WEB-INF/namesTemplate.xhtml"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html">
    <ui:define name="content">
        <!-- =========================== Req Sub Form ================================= -->
        <h:form id="ReqSubForm">
            <!-- =================== Tree Table ================================= -->
            <ui:param name="treeId" value="namePartsTree" />
            <ui:param name="view" value="#{namePartsController.viewRoot}" />
            <ui:param name="selectionMode" value="multiple" />
            <ui:param name="update" value="reqMenu" />
            <p:treeTable 
                id="#{treeId}" 
                value="#{view}" var="nameView"
                selection="#{namePartsController.selectedNodes}"
                selectionMode="#{selectionMode}"
                scrollable="true" 
                scrollWidth="auto"
                resizableColumns="true"
                liveResize="true">
                <f:facet name="header">
                    <p:selectCheckboxMenu 
                        id="viewbutton" 
                        label="View"
                        showHeader="false"
                        value="#{namePartsController.viewFilter.selectedOptions}"
                        style="float:left">
                        <f:selectItems value="#{namePartsController.viewFilter.options}" />
                        <p:ajax 
                            process="@this"
                            listener="#{namePartsController.update()}"
                            update="namePartsTree @form"
                            oncomplete="resizePanel()"/>
                    </p:selectCheckboxMenu>
                    <p:commandButton 
                        value="Collapse" 
                        id="collapse"
                        action="#{namePartsController.onCollapseAll()}"
                        update="namePartsTree"
                        style="float:left"
                        oncomplete="resizePanel()" />
                    <p:commandButton 
                        value="Expand" 
                        id="expand"
                        action="#{namePartsController.onExpandAll()}"
                        update="namePartsTree" 
                        oncomplete="resizePanel()" 
                        style="float:left"/>
                    <p:menuButton 
                        icon="fa fa-aw fa-cog"
                        value="Actions" 
                        id="reqMenu"
                        style="float:right">
                        <p:menuitem
                            value="Add"
                            actionListener="#{namePartsController.prepareOperationDialog('add')}"
                            title="Propose to add a name" icon="fa fa-aw fa-plus-square"
                            oncomplete="PF('wizardName').show()"
                            update=":WizardNameForm"
                            disabled="#{!(namePartsController.can('add'))}"
                            rendered="#{namePartsController.rendered('add')}" />
                        <p:menuitem
                            value="Modify"
                            actionListener="#{namePartsController.prepareOperationDialog('modify')}"
                            title="Propose to modify a name" 
                            icon="fa fa-aw fa-edit"
                            update=":WizardNameForm"
                            oncomplete="PF('wizardName').show()"
                            disabled="#{!(namePartsController.can('modify'))}"
                            rendered="#{namePartsController.rendered('modify')}"/>
                        <p:menuitem
                            value="Delete"
                            actionListener="#{namePartsController.prepareOperationDialog('delete')}"
                            title="Propose to delete names" 
                            icon="fa fa-aw fa-trash"
                            update=":MultNameForm:multName"
                            oncomplete="PF('multName').show()"
                            disabled="#{!(namePartsController.can('delete'))}"
                            rendered="#{namePartsController.rendered('delete')}" />
                        <p:menuitem
                            value="Approve"
                            actionListener="#{namePartsController.prepareOperationDialog('approve')}"
                            title="Approve Requests" 
                            icon="fa fa-aw fa-check"
                            update=":MultNameForm" 
                            oncomplete="PF('multName').show()"
                            disabled="#{!(namePartsController.can('approve'))}"
                            rendered="#{namePartsController.rendered('approve')}" />
                        <p:menuitem 
                            value="Reject"
                            actionListener="#{namePartsController.prepareOperationDialog('reject')}"
                            title="Reject requests" 
                            icon="fa fa-aw fa-ban"
                            update=":MultNameForm"
                            oncomplete="PF('multName').show()"
                            disabled="#{!(namePartsController.can('reject'))}"
                            rendered="#{namePartsController.rendered('reject')}" />
                        <p:menuitem 
                            value="Cancel"
                            actionListener="#{namePartsController.prepareOperationDialog('cancel')}"
                            title="Cancel requests" 
                            icon="fa fa-aw fa-close"
                            update=":MultNameForm:multName"
                            oncomplete="PF('multName').show()"
                            disabled="#{!(namePartsController.can('cancel'))}"
                            rendered="#{namePartsController.rendered('cancel')}" />
                        <p:menuitem
                            value="Check Devices"
                            actionListener="#{namePartsController.prepareOperationDialog('checkDevices')}"
                            title="check and fix device names" 
                            icon="fa fa-aw fa-gear"
                            update=":MultNameForm" oncomplete="PF('multName').show()"
                            disabled="#{!(namePartsController.can('checkDevices'))}"
                            rendered="#{namePartsController.rendered('checkDevices')}" />
                        <p:menuitem 
                            value="View History" title="View History"
                            icon="fa fa-aw fa-search"
                            actionListener="#{namePartsController.prepareHistoryPopup()}"
                            update=":ReqSubForm:historyTable"
                            oncomplete="PF('nameDetail').show()"
                            disabled="#{!(namePartsController.canShowHistory())}" />
                    </p:menuButton>
                </f:facet>
                <p:ajax event="select" update="#{update}" />
                <p:ajax event="unselect" update="#{update}" />
                <p:ajax event="expand" listener="#{treeNodeManager.onNodeExpand}" />
                <p:ajax event="collapse" listener="#{treeNodeManager.onNodeCollapse}" />
                <ui:param name="row" value="#{treeNodeManager.rowData(nameView)}"/>
                <p:column id="fullName" headerText="Full Name" style="width:30%">
                    <ui:include src="/WEB-INF/includes/rowColumn.xhtml">
                        <ui:param name="columnData" value="#{row.fullName}" />
                        <ui:param name="columnDataTitle" value="#{row.fullName}" />
                    </ui:include>
                </p:column>
                <p:column id="mnemonic" headerText="Mnemonic" style="width:10%">
                    <ui:include src="/WEB-INF/includes/rowColumn.xhtml">
                        <ui:param name="columnData" value="#{row.mnemonic}" />
                        <ui:param name="columnDataTitle" value="#{row.mnemonic}" />
                    </ui:include>
                </p:column>
                <p:column id="description" headerText="Description" style="width:50%">
                    <ui:include src="/WEB-INF/includes/rowColumn.xhtml">
                        <ui:param name="columnData" value="#{row.description}" />
                        <ui:param name="columnDataTitle" value="#{row.description}" />
                    </ui:include>		
                </p:column>

                <p:column id="status" headerText="Status" style="width: 10%">
                    <h:outputText value="#{row.getStatus()}" styleClass="#{row.getStatusStyle()}"/>
                    <!-- 			<h:outputLink id="pendingComment" value="#" -->
                    <!-- 				rendered="#{namePartsController.hasPendingComment(nameView)}"> -->
                    <!-- 				<h:outputText styleClass="ui-icon ui-icon-info" -->
                    <!-- 					style="display:inline-block; margin-left:10px !important; vertical-align:bottom !important;" /> -->
                    <!-- 			</h:outputLink> -->
                    <!-- 			<p:tooltip for="pendingComment"> -->
                    <!-- 				<h:outputText -->
                    <!-- 					value="#{namePartsController.getPendingComment(nameView)}" -->
                    <!-- 					style="white-space: pre;" escape="false" /> -->
                    <!-- 			</p:tooltip> -->
                </p:column>
            </p:treeTable>                
            <!-- =================== History ================================= -->
            <ui:include src="/WEB-INF/includes/history.xhtml">
                <ui:param name="historyHandler"
                          value="#{namePartsController.historyRevisionsAsRowData}" />
            </ui:include>
        </h:form>
        <!-- ===================Wizard=================================== -->
        <ui:include src="/WEB-INF/includes/parts-wizard.xhtml">
        </ui:include>
        <!-- ===================Multiple selection Form================================= -->
        <ui:include src="/WEB-INF/includes/operationtreeform.xhtml">
            <ui:param name="formId" value="MultNameForm" />
            <ui:param name="controller" value = "#{namePartsController}"/>
            <ui:param name="widgetId" value="multName" />
            <ui:param name="update" value =":ReqSubForm:namePartsTree:reqMenu :ReqSubForm:namePartsTree @form :menu:messages"/> 
            <ui:param name ="complete" value="stop()"/>
        </ui:include>
    </ui:define>
</ui:composition>