NamingConventionTool/src/main/java/org/openepics/names/ui/common/LoginController.java
package org.openepics.names.ui.common;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import org.openepics.names.business.NameType;
import org.openepics.names.services.SessionService;
import org.openepics.names.ui.parts.NamePartsController;
import se.esss.ics.rbac.loginmodules.service.Message;

/**
 * A UI controller bean for the login / logout button and form.
 *
 * @author Vasu V
 * @author K. Rathsman
 */
@ManagedBean
@ViewScoped
public class LoginController implements Serializable {

    private static final long serialVersionUID = 7124872676453151325L;
    private static final Logger LOGGER = Logger.getLogger(LoginController.class.getName());
    @Inject
    private SessionService sessionService;
    private String inputUsername;
    private String inputPassword;

    @PostConstruct
    public synchronized void init() {

    }

    public String getActiveIndex() {
        String viewId = FacesContext.getCurrentInstance().getViewRoot().getViewId();
        switch (viewId) {
            case "/index.xhtml":
                return "0";
            case "/about.xhtml":
                return "1";
            case "/devices.xhtml":
                return "2";
            case "/parts.xhtml":
                String type = FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("type");
                if (type == null) {
                    FacesContext facesContext = FacesContext.getCurrentInstance();
                    NamePartsController namePartsController = (NamePartsController) facesContext.getApplication().getExpressionFactory().createValueExpression(facesContext.getELContext(), "#{namePartsController}", Object.class).getValue(facesContext.getELContext());
                    type = namePartsController.getType();
                }
                if (type != null && type.equals(NameType.AREA_STRUCTURE.toString())) {
                    return "3";
                } else if (type != null && type.equals(NameType.DEVICE_STRUCTURE.toString())) {
                    return "4";
                } else {
                    return "0";
                }
            case "/help.xhtml":
                return "5";
            default:
                return "0";
        }
    }

    public void prepareLoginPopup() {
        inputUsername = null;
        clearPassword();
    }

    public void clearPassword() {
        inputPassword = null;
    }

    public synchronized void signIn() throws IOException {
        try {
            Message m = sessionService.login(inputUsername, inputPassword);
            if (m.isSuccessful()) {
                LOGGER.log(Level.INFO, "Login successful for " + getUsername());
            } else {
                showMessage(new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed to sign in", m.getMessage()));
                LOGGER.log(Level.INFO, "Login failed for " + inputUsername);
            }
        } catch (Exception e) {
            showMessage(new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed to sign in", e.getMessage()));
            LOGGER.log(Level.SEVERE, "Cannot sign in", e.getMessage());

        } finally {
            clearPassword();
            sessionService.update();
        }
    }

    public boolean isLoggedIn() {
        return sessionService.isLoggedIn();
    }

    public String getUsername() {
        return sessionService.getUsername();
    }

    public synchronized String signOut() {
        try {
            Message m = sessionService.logout();
            if (m.isSuccessful()) {
                LOGGER.log(Level.INFO, "Logout successful");

            } else {
                showMessage(new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed to sign out", m.getMessage()));
                LOGGER.log(Level.SEVERE, "Failed to sign out", m.getMessage());
            }
        } catch (Exception e) {
            showMessage(new FacesMessage(FacesMessage.SEVERITY_ERROR, "Failed to sign out", e.getMessage()));
            LOGGER.log(Level.SEVERE, "Failed to sign out ", e.getMessage());

        } finally {
            prepareLoginPopup();
            sessionService.update();
        }
        return FacesContext.getCurrentInstance().getViewRoot().getViewId();

    }

    public String getInputUsername() {
        return inputUsername;
    }

    public void setInputUsername(String inputUsername) {
        this.inputUsername = inputUsername;
    }

    public String getInputPassword() {
        return inputPassword;
    }

    public void setInputPassword(String inputPassword) {
        this.inputPassword = inputPassword;
    }

    /**
     * shows the faces message
     *
     * @param message the faces message
     */
    public void showMessage(FacesMessage message) {
        FacesContext.getCurrentInstance().addMessage(null, message);
    }
}

NamingConventionTool/src/main/webapp/WEB-INF/namesTemplate.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <link href="resources/css/themeESS.css" rel="stylesheet" type="text/css" />
        <script type="text/javascript">

            function resizePanel() {
// 			$('#indexDiv').css({
// 				"height" : window.innerHeight - menusHeight
// 			});
// 			$('#apiManualDiv').css({
// 				"height" : window.innerHeight - menusHeight
// 			});
                var menusHeight = $('#Header').outerHeight(true) + $('#menu').outerHeight(true) + $('#loginPanel').outerHeight(true);
                var panelHeight = window.innerHeight - menusHeight - 26;
                this.setTreeTableScrollHeight('#ReqSubForm\\:namePartsTree', panelHeight);
//			this.setDataTableScrollHeight('#ManageNameForm\\:devicesTree',panelHeight);
            }

            function setTreeTableScrollHeight(treeTableId, panelHeight) {
                var headerHeight = $(treeTableId + ' .ui-treetable-scrollable-header').outerHeight(true);
                var footerHeight = $(treeTableId + ' .ui-treetable-scrollable-footer').outerHeight(true);
                var scrollHeight = panelHeight - headerHeight - footerHeight;
                var scrollBody = $(treeTableId + ' .ui-treetable-scrollable-body');
                scrollBody.height(scrollHeight);
            }

            function setDataTableScrollHeight(dataTableId, panelHeight) {
                var headerHeight = $(dataTableId + ' .ui-datatable-scrollable-header').outerHeight(true);
                var footerHeight = $(dataTableId + ' .ui-datatable-scrollable-footer').outerHeight(true);
                var scrollHeight = panelHeight - headerHeight - footerHeight;
                var scrollBody = $(dataTableId + ' .ui-datatable-scrollable-body');
                scrollBody.height(scrollHeight);
            }

            $(window).resize(function () {
                resizePanel();
            });

            $(window).ready(function () {
                resizePanel();
            });

//          Bug workaround  https://github.com/primefaces/primefaces/issues/2448
            $.extend($.ui.keyCode, {
                NUMPAD_ENTER: 108
            });

            function refresh() {
                PF('deviceTable').filter();
                resizePanel();
            }
            function start() {
                PF('statusDialog').show();
            }

            function stop() {
                PF('statusDialog').hide();
            }

            function reload() {
                location.reload();
            }

//		function displayMnemonicLengthWarning() {
//			if ($('#WizardNameForm\\:icode').val().length > 4) {
//				$('#WizardNameForm\\:mnemonicLengthWarning').css({
//					"display" : "block"
//				});
//			} else {
//				$('#WizardNameForm\\:mnemonicLengthWarning').css({
//					"display" : "none"
//				});
//			}
//		}

            function displayIndexLengthWarningOnAdd() {
                if ($('#addDeviceNameForm\\:instanceIndex').val().length > 3) {
                    $('#addDeviceName\\:indexLengthWarning').css({
                        "display": "block"
                    });
                } else {
                    $('#addDeviceName\\:indexLengthWarning').css({
                        "display": "none"
                    });
                }
            }

            function displayIndexLengthWarningOnMod() {
                if ($('#modDeviceNameForm\\:instanceIndex').val().length > 3) {
                    $('#modDeviceName\\:indexLengthWarning').css({
                        "display": "block"
                    });
                } else {
                    $('#modDeviceName\\:indexLengthWarning').css({
                        "display": "none"
                    });
                }
            }

        </script>	
        <link rel="shortcut icon" href="/resources/images/favicon.ico" type="image/x-icon"/>
        <title>Naming Service</title>
    </h:head>

    <h:body>
        <p:outputPanel id="full" layout="block" >
            <h:form id="Header">
                <h:panelGroup id="panel" layout="block" > 
                    <h:outputText id ="title" value="#{applicationInfo.get('title')}"/>
                    <h:panelGroup id="left" style="float:left" layout="span">
                        <p:graphicImage id = "logo" library="images" name="logo.png" />
                    </h:panelGroup>
                    <h:panelGroup id="right" rendered="#{loginController.loggedIn}" style="float:right" layout="span">
                        <p:button  href="#{applicationInfo.get('wiki')}"  target="blank" title="#{applicationInfo.get('wiki')}" value="Wiki" icon="fa fa-aw fa-book"/>
                        <p:button  id="issues" href="#{applicationInfo.get('issues')}"  target="blank" value="Issues" icon="fa fa-aw fa-exclamation-circle" title="#{applicationInfo.get('issues')}"/>
                        <p:commandButton  id="signout" update =":full" action="#{loginController.signOut()}" oncomplete="location.reload(true)" process="@this" value="#{loginController.username}" icon="fa fa-aw fa-sign-out" title="Sign Out"/>                        
                    </h:panelGroup>
                </h:panelGroup>
                <!--                <f:facet name="left"><span><p:graphicImage id = "logo" library="images" name="logo.png" /></span><span></span></f:facet>
                                    <f:facet name="right">
                                        
                 
                                    </f:facet>
                                </p:toolbar>-->
            </h:form>

            <ui:include src="/WEB-INF/includes/menubar.xhtml" />
            <ui:include src="/WEB-INF/includes/login.xhtml"/>
            <p:outputPanel id="content" rendered="#{loginController.loggedIn}" >
                <ui:insert name="content">Content</ui:insert>
            </p:outputPanel>
        </p:outputPanel>
        <p:dialog modal="true" widgetVar="statusDialog" showHeader="false"
                  draggable="false" closable="false" resizable="false">
            <p:graphicImage value="/resources/images/ajax-loader.gif" />
        </p:dialog>
    </h:body>
</html>