NamingConventionTool/src/main/java/org/openepics/names/ui/common/ErrorDialogController.java
/*
 * Copyright (C) 2020 European Spallation Source ERIC.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package org.openepics.names.ui.common;

import com.google.common.collect.ImmutableMap;
import com.google.common.net.HttpHeaders;
import org.apache.commons.io.IOUtils;
import org.apache.commons.lang3.StringUtils;
import org.openepics.names.services.SessionService;
import org.openepics.names.util.AppProperties;
import org.openepics.names.util.MailService;
import org.openepics.names.util.UiUtility;

import javax.faces.application.Application;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.servlet.http.HttpServletRequest;
import java.io.InputStream;
import java.io.Serializable;
import java.util.Collections;
import java.util.Map;
import java.util.ResourceBundle;

/**
 * Controller bean class for error dialogs.
 *
 * @author <a href="mailto:zoltan.runyo@ess.eu">Zoltan Runyo</a>
 * @author Lars Johansson
 */
@Named
@ViewScoped
public class ErrorDialogController implements Serializable {

    private static final String BR      = "<br/>";
    private static final String SUBJECT = "Bug report";

    private String header;
    private String message;
    private String details;
    private String stackTrace;
    private String comment;
    private boolean unexpectedError;
    @Inject
    private AppProperties properties;

    @Inject
    private MailService mailService;
    @Inject
    private SessionService sessionService;

    public boolean isHeaderEmpty() {
    	return StringUtils.isEmpty(header);
    }

    public boolean isMessageEmpty() {
    	return StringUtils.isEmpty(message);
    }

    public boolean isDetailsEmpty() {
    	return StringUtils.isEmpty(details);
    }

    public String getHeader() {
        return header;
    }

    public void setHeader(String header) {
        this.header = header;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }

    public void setStackTrace(String stackTrace) {
        this.stackTrace = stackTrace;
    }

    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public boolean isUnexpectedError() {
        return unexpectedError;
    }

    /**
     * Return if feedback UI is to be shown.
     *
     * @return if feedback UI is to be shown
     */
    public boolean showFeedbackUI() {
        return StringUtils.isNotEmpty(getSupportEmail()) && unexpectedError;
    }

    public void setUnexpectedError(boolean unexpectedError) {
        this.unexpectedError = unexpectedError;
    }

    /**
     * Report behavior to support email and user.
     */
    public void reportBehavior() {
        String supportEmail = getSupportEmail();
        String attachment = stackTrace;
        Map<String, String> requestHeaders = getRequestHeaders();
        String header = "Application: " + getMessagesProperty("title") + BR +
                "Version: " + getMessagesProperty("version") + BR +
                "System: " + requestHeaders.get(HttpHeaders.HOST) + BR +
                "User agent: " + requestHeaders.get(HttpHeaders.USER_AGENT) + "<br/><br/>";
        String body = header + "User comment: " + (StringUtils.isNotEmpty(comment) ?
                comment.replaceAll("\\r\\n|\\r|\\n", BR) : "-");
        InputStream attachmentStream = IOUtils.toInputStream(attachment);

        try {
            if (MailService.IS_MAIL_NOTIFICATION_ENABLED) {
                mailService.sendMail(Collections.singletonList(supportEmail), sessionService.getUsername(),
                        SUBJECT, body, Collections.singletonList(attachmentStream),
                        Collections.singletonList("stack_trace.txt"), true);
                UiUtility.showInfoMessage("Email sent to support team.");
            } else {
                UiUtility.showErrorMessage("Sending email to support team is disabled!",
                        "Please contact system administrator!");
            }
            dismiss();
        } catch (Exception e) {
            UiUtility.showErrorMessage("Failed to send email to support team!",
                    "Please try again!");
        }

    }

    public String getSupportEmail() {
        return properties.getSupportEmail();
    }

    /**
     * Dismiss error message.
     */
    public void dismiss() {
        UiUtility.dismissErrorMessage();
        details = null;
        comment = null;
    }

    private String getMessagesProperty(String key) {
        FacesContext context = FacesContext.getCurrentInstance();
        Application app = context.getApplication();
        ResourceBundle messages = app.getResourceBundle(context, "appInfo");
        return messages.getString(key);
    }

    private Map<String, String> getRequestHeaders() {
        HttpServletRequest request =
                (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        return ImmutableMap.of(HttpHeaders.USER_AGENT, request.getHeader(HttpHeaders.USER_AGENT),
                HttpHeaders.HOST, request.getHeader(HttpHeaders.HOST));
    }
}

NamingConventionTool/src/main/java/org/openepics/names/ui/common/LoginController.java
/*
 * Copyright (c) 2014 European Spallation Source ERIC.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package org.openepics.names.ui.common;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import org.openepics.names.business.NameType;
import org.openepics.names.services.SessionService;
import org.openepics.names.ui.parts.NamePartsController;
import org.openepics.names.util.UiUtility;

import se.esss.ics.rbac.loginmodules.service.Message;

/**
 * A UI controller bean for the login / logout button and form.
 *
 * @author Vasu V
 * @author K. Rathsman
 */
@ManagedBean
@ViewScoped
public class LoginController implements Serializable {

    private static final long serialVersionUID = 7124872676453151325L;

    private static final String FAILED_TO_SIGN_IN = "Failed to sign in";
    private static final String FAILED_TO_SIGN_OUT = "Failed to sign out";

    private static final Logger LOGGER = Logger.getLogger(LoginController.class.getName());

    @Inject
    private SessionService sessionService;
    private String inputUsername;
    private String inputPassword;

    /**
     * Initializes the bean.
     */
    @PostConstruct
    public synchronized void init() {

    }

    public String getActiveIndex() {
        String viewId = FacesContext.getCurrentInstance().getViewRoot().getViewId();
        switch (viewId) {
            case "/index.xhtml":
                return "0";
            case "/devices.xhtml":
                return "1";
            case "/parts.xhtml":
                String type =
                    FacesContext.getCurrentInstance().getExternalContext().getRequestParameterMap().get("type");
                if (type == null) {
                    FacesContext facesContext = FacesContext.getCurrentInstance();
                    NamePartsController namePartsController =
                            (NamePartsController) facesContext.getApplication().getExpressionFactory()
                                    .createValueExpression(
                                            facesContext.getELContext(), "#{namePartsController}", Object.class)
                                    .getValue(facesContext.getELContext());
                    type = namePartsController.getType();
                }
                if (type.equals(NameType.SYSTEM_STRUCTURE.toString())) {
                    return "2";
                } else if (type.equals(NameType.DEVICE_STRUCTURE.toString())) {
                    return "3";
                } else {
                    return "0";
                }
            case "/help.xhtml":
                return "4";
            default:
                return "0";
        }
    }

    /**
     * Prepares for the login popup.
     */
    public void prepareLoginPopup() {
        inputUsername = null;
        clearPassword();
    }

    /**
     * Clears the password.
     */
    public void clearPassword() {
        inputPassword = null;
    }

    /**
     * Sign in of user, session is updated.
     *
     * @throws IOException if user cannot sign in
     */
    public synchronized void signIn() throws IOException {
        try {
            Message m = sessionService.login(inputUsername, inputPassword);
            if (m.isSuccessful()) {
                LOGGER.log(Level.INFO, "Login successful for " + getUsername());
            } else {
                UiUtility.showErrorMessage(FAILED_TO_SIGN_IN, m.getMessage());
                LOGGER.log(Level.INFO, "Login failed for " + inputUsername);
            }
        } catch (Exception e) {
            UiUtility.showErrorMessage(FAILED_TO_SIGN_IN, e.getMessage());
            LOGGER.log(Level.SEVERE, "Cannot sign in", e.getMessage());

        } finally {
            clearPassword();
            sessionService.update();
        }
    }

    /**
     * Return if the user is signed in for application.
     *
     * @return if the user is signed in for application
     */
    public boolean isLoggedIn() {
        return sessionService.isLoggedIn();
    }

    /**
     * Return user name.
     * @return user name
     */
    public String getUsername() {
        return sessionService.getUsername();
    }

    /**
     * Sign in of user, session is updated.
     *
     * @return the view identifier for this view
     */
    public synchronized String signOut() {
        try {
            Message m = sessionService.logout();
            if (m.isSuccessful()) {
                LOGGER.log(Level.INFO, "Logout successful");

            } else {
                UiUtility.showErrorMessage(FAILED_TO_SIGN_OUT, m.getMessage());
                LOGGER.log(Level.SEVERE, FAILED_TO_SIGN_OUT, m.getMessage());
            }
        } catch (Exception e) {
            UiUtility.showErrorMessage(FAILED_TO_SIGN_OUT, e.getMessage());
            LOGGER.log(Level.SEVERE, FAILED_TO_SIGN_OUT, e.getMessage());
        } finally {
            prepareLoginPopup();
            sessionService.update();
        }
        return FacesContext.getCurrentInstance().getViewRoot().getViewId();

    }

    public String getInputUsername() {
        return inputUsername;
    }

    public void setInputUsername(String inputUsername) {
        this.inputUsername = inputUsername;
    }

    public String getInputPassword() {
        return inputPassword;
    }

    public void setInputPassword(String inputPassword) {
        this.inputPassword = inputPassword;
    }

}

NamingConventionTool/src/main/webapp/WEB-INF/includes/devices-datatable-partcolumn-deviceName.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://java.sun.com/jsf/html">

    <ui:param name="nameView" value="#{record[part]}"/>
    <ui:param name="row" value="#{treeNodeManager.rowData(nameView)}" />
    <ui:param name="name" value="#{row[element]}"/>
    <ui:param name="tooltip" value="#{row[tooltipElement]}"/>
    <ui:param name="sortBy" value="#{name.toString()}"/>
    <p:column headerText="#{title}" sortBy="#{sortBy}" filterBy="#{sortBy}" filterMatchMode="contains" filterFunction="#{treeNodeManager.filterByRegex}" visible="#{visible}">
        <ui:include src="/WEB-INF/includes/rowColumn.xhtml">
            <ui:param name="columnData" value="#{name}" />
            <ui:param name="columnDataTitle" value ="#{tooltip}" />
        </ui:include>

        <p:link  target="_blank" 
                 href="#{treeNodeManager.chessURL}#{name}" title="Open in Chess" includeViewParams = "true">
            <h:outputText  
                style="display:inline-block; vertical-align:bottom !important; margin-left: 1ex;"
                styleClass="ui-icon ui-icon-extlink"/>
        </p:link>
    </p:column>

</ui:composition>

NamingConventionTool/src/main/webapp/WEB-INF/includes/devices-datatable-partcolumn.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

	<ui:param name="nameView" value="#{record[part]}"/>
	<ui:param name="row" value="#{treeNodeManager.rowData(nameView)}" />
	<ui:param name="name" value="#{row[element]}"/>
	<ui:param name="tooltip" value="#{row[tooltipElement]}"/>
	<ui:param name="sortBy" value="#{name.toString()}"/>
	<p:column headerText="#{title}" sortBy="#{sortBy}" filterBy="#{sortBy}" filterMatchMode="contains" visible="#{visible}">
		<ui:include src="/WEB-INF/includes/rowColumn.xhtml">
			<ui:param name="columnData" value="#{name}" />
			<ui:param name="columnDataTitle" value ="#{tooltip}" />
		</ui:include>
	</p:column>

</ui:composition>

NamingConventionTool/src/main/webapp/WEB-INF/includes/error-dialog.xhtml
<!--
  ~ Copyright (C) 2020 European Spallation Source ERIC.
  ~
  ~ This program is free software; you can redistribute it and/or
  ~ modify it under the terms of the GNU General Public License
  ~ as published by the Free Software Foundation; either version 2
  ~ of the License, or (at your option) any later version.
  ~
  ~ This program is distributed in the hope that it will be useful,
  ~ but WITHOUT ANY WARRANTY; without even the implied warranty of
  ~ MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  ~ GNU General Public License for more details.
  ~
  ~ You should have received a copy of the GNU General Public License
  ~ along with this program; if not, write to the Free Software
  ~ Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
  -->

<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://java.sun.com/jsf/html"
                xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:form id="errorDialogForm">
        <p:growl id="errorDialogGrowl" showDetail="true" life="5000"/>

        <p:dialog widgetVar="errorDialog" id="errorDialog" modal="true" resizable="false" closable="true" width="520" dynamic="true">
            <f:facet name="header">
                <h:graphicImage url="/resources/images/error.png" width="16" height="16" style="vertical-align: middle;"/>
                <p:outputLabel value="#{errorDialogController.unexpectedError ? 'Unexpected error' : 'Error'}" style="vertical-align: bottom; margin-left: 5px"/>
            </f:facet>
            <div class="ui-fluid">
                <p:panelGrid styleClass="dialog-grid-panel noBorders">
                    <p:row>
                        <p:column styleClass="dialog-labels-width-1" style="padding-top: 1.2em; vertical-align: top;">
                            <p:outputLabel value="Details:" style="font-weight:bold"/>
                        </p:column>
                        <p:column>
                            <p:scrollPanel style="width:400px;height:80px">
								<p>
                                    <h:panelGroup rendered="#{!errorDialogController.headerEmpty}">#{errorDialogController.header}<br/></h:panelGroup>
                                    <h:panelGroup rendered="#{!errorDialogController.messageEmpty}">#{errorDialogController.message}<br/></h:panelGroup>
                                    <h:panelGroup rendered="#{!errorDialogController.detailsEmpty}">#{errorDialogController.details}</h:panelGroup>
								</p>
                            </p:scrollPanel>
                        </p:column>
                    </p:row>
                    <p:row rendered="#{errorDialogController.showFeedbackUI()}">
                        <p:column styleClass="dialog-labels-width-1" style="padding-top: 0.5em; vertical-align: top;">
                            <p:outputLabel value="Comment (optional):" style="font-weight:bold"/>
                        </p:column>
                        <p:column>
                            <p:inputTextarea rows="5" maxlength="5000" autoResize="false"
                                             value="#{errorDialogController.comment}"/>
                        </p:column>
                    </p:row>
                </p:panelGrid>
            </div>

            <p:panel style="text-align: right; padding: 0; border: 0;" styleClass="dialogButtonPanel">
                <p:commandButton  value="Report behavior" icon="ui-icon-mail-closed"
                                  rendered="#{errorDialogController.showFeedbackUI()}"
                                  action="#{errorDialogController.reportBehavior}" update="errorDialogGrowl"
                                  onstart="PF('statusDialog').show();" oncomplete="PF('statusDialog').hide();"/>
                <p:commandButton value="Close" icon="ui-icon-close" styleClass="dialogButton"
                                 action="#{errorDialogController.dismiss}" />
            </p:panel>
        </p:dialog>
    </h:form>
</ui:composition>

NamingConventionTool/src/main/webapp/WEB-INF/includes/filterWizard.xhtml
<?xml version='1.0' encoding='UTF-8' ?>

<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:h="http://java.sun.com/jsf/html">

    <h:form id="FilterDeviceNameForm">
        <p:dialog id="#{widgetId}" widgetVar="#{widgetId}" modal="true"
                  dynamic="false" header="Set global filter" width="800"
                  onShow="PF('wiz').loadStep('systemTab',true)">
            <p:wizard id="wizardId" widgetVar="wiz" showStepStatus="false">

                <p:tab id="systemTab" title="System">
                    <h3>
                        <h:outputText
                            value="1. Which systems of the facility is relevant to you?" />
                    </h3>
                    <p>The customized filter settings will be saved for the
                        remainder of this session.</p>

                    <p:separator />
                    <p:commandButton
                        value="Select All"
                        style="z-index:100"
                        action="#{deviceTableController.filterWizard.onSystemStructureSelectAll}"
                        update="systemtree" />
                    <p:commandButton
                        value="Unselect All"
                        style="z-index:100"
                        action="#{deviceTableController.filterWizard.onSystemStructureUnselectAll}"
                        update="systemtree" />
                    <p:tree
                        id ="systemtree"
                        value="#{deviceTableController.filterWizard.systemStructure}"
                        selectionMode="checkbox"
                        var="systemView"
                        dynamic="true">
                        <p:ajax event="select" listener="#{treeNodeManager.onFilterNode}" />
                        <p:ajax event="unselect"
                                listener="#{treeNodeManager.onUnfilterNode}" />
                        <p:ajax event="expand" listener="#{treeNodeManager.onNodeExpand}" />
                        <p:ajax event="collapse"
                                listener="#{treeNodeManager.onNodeCollapse}" />

                        <ui:param name="row" value="#{treeNodeManager.rowData(systemView)}" />
                        <p:treeNode>
                            <ui:include src="/WEB-INF/includes/rowColumn.xhtml">
                                <ui:param name="columnData" value="#{row.combined}" />
                                <ui:param name="columnDataTitle" value="#{row.description}" />
                            </ui:include>
                        </p:treeNode>
                    </p:tree>
                    <p:separator />
                    <p:messages showDetail="true" >
                        <p:autoUpdate disabled="false"/>
                    </p:messages>
                    <div align="right">
                        <p:commandButton value="Ok"
                                         process="@this"
                                         update=":ManageNameForm :ManageNameForm:devicesTree:ncReqMenu @form"
                                         style="float:right"
                                         action="#{deviceTableController.update()}"
                                         onclick="start()"
                                         oncomplete="stop(); PF('deviceTable').filter()" />
                    </div>


                </p:tab>
                <p:tab id="deviceTab" title="Device">
                    <h3>
                        <h:outputText value="2. What kind of devices are relevant to you?" />
                    </h3>
                    <p>The customized filter settings will be saved for the
                        remainder of this session.</p>
                    <p:separator />
                    <p:commandButton
                        value="Select All"
                        style="z-index:100"
                        action="#{deviceTableController.filterWizard.onDeviceStructureSelectAll}"
                        update="devicetree" />
                    <p:commandButton
                        value="Unselect All"
                        style="z-index:100"
                        action="#{deviceTableController.filterWizard.onDeviceStructureUnselectAll}"
                        update="devicetree" />
                    <p:tree
                        id="devicetree"
                        value="#{deviceTableController.filterWizard.deviceStructure}"
                        selectionMode="checkbox" var="deviceView"
                        dynamic="true">
                        <p:ajax event="select" listener="#{treeNodeManager.onFilterNode}" />
                        <p:ajax event="unselect"
                                listener="#{treeNodeManager.onUnfilterNode}" />
                        <p:ajax event="expand" listener="#{treeNodeManager.onNodeExpand}" />
                        <p:ajax event="collapse"
                                listener="#{treeNodeManager.onNodeCollapse}" />

                        <ui:param name="row"
                                  value="#{treeNodeManager.rowData(deviceView)}" />
                        <p:treeNode>
                            <ui:include src="/WEB-INF/includes/rowColumn.xhtml">
                                <ui:param name="columnData" value="#{row.combined}" />
                                <ui:param name="columnDataTitle" value="#{row.description}" />
                            </ui:include>
                        </p:treeNode>
                    </p:tree>
                    <p:separator />
                    <p:messages showDetail="true" >
                        <p:autoUpdate disabled="false"/>
                    </p:messages>
                    <div align="right">
                        <p:commandButton
                            value="Ok"
                            process="@this"
                            update=":ManageNameForm :ManageNameForm:devicesTree:ncReqMenu @form"
                            style="float:right"
                            action="#{deviceTableController.update()}"
                            onclick="start()"
                            oncomplete="stop(); PF('deviceTable').filter()" />
                    </div>
                </p:tab>
            </p:wizard>
        </p:dialog>
    </h:form>
</ui:composition>

NamingConventionTool/src/main/webapp/WEB-INF/includes/login.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:f="http://java.sun.com/jsf/core"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://java.sun.com/jsf/html">

    <h:form id="loginForm">
        <!-- 	<p:growl globalOnly="true" id="msgs" showDetail="true" -->
        <!-- 					sticky="false" life="10000" /> -->
        <p:dialog id="loginDialog" widgetVar="loginDialog" header="Sign In" modal="true" visible="#{!loginController.loggedIn}" closable="false" >
            <h:panelGrid id="grid" columns="2">
                <p:outputLabel for="userid" value="Username:" />
                <h:panelGroup>
                    <p:inputText id="userid" value="#{loginController.inputUsername}"
                                 label="Username"/>
                    <p:watermark for="userid" value="Enter username" />
                    <p:message for="userid" />
                </h:panelGroup>
                <p:outputLabel for="passwd" value="Password:" />
                <h:panelGroup>
                    <p:password id="passwd" value="#{loginController.inputPassword}"
                                label="Password" />
                    <p:watermark for="passwd" value="Enter password" />
                    <p:message for="passwd" />
                </h:panelGroup>
                <f:facet name="footer">
                    <p:separator />					
                    <p:commandButton id="submit" value="Sign In" update=":full :loginForm"
                                     action="#{loginController.signIn()}" style="float: right"/>
                    <p:defaultCommand target="submit" />
                </f:facet>
            </h:panelGrid>
        </p:dialog>
    </h:form>


</ui:composition>

NamingConventionTool/src/main/webapp/WEB-INF/includes/menubar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
                xmlns:ui="http://java.sun.com/jsf/facelets"
                xmlns:p="http://primefaces.org/ui"
                xmlns:h="http://java.sun.com/jsf/html">

    <h:form id="menu" >
        <p:growl globalOnly="true" id="messages" showDetail="true"
                 sticky="false" life="10000" />
        <p:tabMenu id="mainMenu" activeIndex="${loginController.activeIndex}" rendered="#{loginController.loggedIn}">
            <p:menuitem value="Home" icon="fa fa-aw fa-home" outcome="index.xhtml"/>
            <p:menuitem value="ESS Name Registry" icon="fa fa-aw fa-tachometer" outcome="devices.xhtml" onclick="start()" oncomplete="stop()"/>
            <p:menuitem value="System Structure" icon="fa fa-aw fa-sitemap" outcome="parts.xhtml?type=systemStructure" onclick="start()" oncomplete="stop()"/>
            <p:menuitem value="Device Structure" icon="fa fa-aw fa-sitemap" outcome="parts.xhtml?type=deviceStructure" onclick="start()" oncomplete="stop()"/>
            <p:menuitem value="Help" icon="fa fa-aw fa-question-circle" outcome="help.xhtml"/>
        </p:tabMenu>
    </h:form>

</ui:composition>

NamingConventionTool/src/main/webapp/WEB-INF/includes/rowColumn.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:h="http://java.sun.com/jsf/html">

	<h:outputText value="#{columnData.pending}" styleClass="#{columnData.pendingStyle}" title = "#{columnDataTitle.pending}"/>
	<h:outputText value="#{columnData.pendingSeparator}" />
	<h:outputText value="#{columnData.approved}" styleClass="#{columnData.approvedStyle}" title = "#{columnDataTitle.approved}"  />
	<h:outputText value="#{columnData.cancelledSeparator}" />
	<h:outputText value="#{columnData.cancelled}" styleClass="#{columnData.cancelledStyle}" title = "#{columnDataTitle.cancelled}" />
</ui:composition>